### ISSUE TITLE
Unit test error during udacity submit

### ISSUE THREAD

**Issue by vasiliy-mikhailov** [udacity/aind2-rnn#5]
Units tests use clean**ed**_text from my_answers, while it named clean_text both in my_answers.py and RNN_project.ipynb

Udacity submit output:
Failed Test: Step 3: Clean up a large text corpus
----------------------------------------------------------------------
NameError: name 'cleaned_text' is not defined

**Comment by cgearhart** [comment]
The name change is intentional, and should be correct in the latest version.
