### ISSUE TITLE
Unit tests use incorrect parameter name for build_part1_RNN()

### ISSUE THREAD

**Issue by vasiliy-mikhailov** [udacity/aind2-rnn#6]
Correct specification of build_part1_RNN(): def build_part1_RNN(step_size, window_size)
Unit tests performed during udacity submit do not supply window_size, that leads to following error:

Failed Test: Step 2: Create a simple RNN model for regression
----------------------------------------------------------------------
TypeError: build_part1_RNN() missing 1 required positional argument: 'window_size'

**Comment by cgearhart** [comment]
The function signature change is intentional, and should be correct in the latest version.
