### ISSUE TITLE
build_part2_RNN()

### ISSUE THREAD

**Issue by bpfliegel** [udacity/aind2-rnn#7]
It is not called anywhere...

**Comment by bpfliegel** [comment]
The whole refactoring seems untested... see other errors. Why do I get 'AssertionError: False is not true : Output value (y) should have exactly 1 dimension.' when the last layer is expected to be a Dense(1)? In which argument is len(chars) passed? Try to do this project and submit through udacity-pa, won't be possible.

**Comment by cgearhart** [comment]
May have been an oversight; the function is called in the last block before section 2.7 in the latest version.
